### PR TITLE
Fix v1.1.0

### PR DESCRIPTION
**Pull request by mvarewyck**

### CODE REVIEW

**Comment by mvarewyck** [comment]
* Wait for inbo/aspbo#252: data update
Then remove [this](https://github.com/inbo/alien-species-portal/blob/fix_v1.1.0/alienSpecies/inst/app/serverFiles/serverSpecies.R#L221-L232). Might need an additional renaming of some columns as currently integrated in `createTabularData()`

* Wait for inbo/aspbo#253: translations update

**Comment by SanderDevisscher** [comment]
Waiting for inbo/aspbo#253 seems unnecessary

**Comment by SanderDevisscher** [comment]
building app: https://github.com/inbo/alien-species-portal/actions/runs/11073685801/job/30770775763

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
@mvarewyck when testing the bins for the invasion history I found some weird behaviour:

I'm testing with _Lithobates catesbeianus_

What happens:

1. When I select "quantiles" BinType with the default nBins (=5) I get the following error:
`'breaks' are not unique`
2. I thus reduce the nBins to 4 which results in 4 bins see below:
image
but upon clicking binConfirm the binType switches to "user defined" and the last bin expands to [lower limit - max value] see below:
image
The issue does only occur the first time you click binConfirm. Changing the region seems to reset the issue.  
3. Typing custom bin breaks seems not to work fluently the textbox seems to unselect everytime I type a digit
4. User defined bins are not reflected in bin graph, see below:
image
6. Last bin starts empty when binType = "user defined" falsely stating there is no data
7. Last binSize readablility is poor
8. Legend & bins do not match, see below:
image
image


What should happen:

- [x] 1. Quantiles implies 4 bins so nBins slide should be disabled for quantiles and it should be fixed to 4
- [x] 2. The bin sizes should remain fixed once binConfirm is clicked
- [x] 3. Typing in bin breaks should go without a hitch 
- [x] 4. user defined bins should be reflected in graph
- [ ] 5. last bin should start with max value
- [x] 6. if possible change last binSize text color to white ?
- [x] 7. Bins should be included into the legend even if they are empty

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
- [x] The Harmonia+ link should be placed under risk assessment 
- [x] The Harmonia+ link should get "Harmonia+ Risk Assessment" as link text

**Comment by mvarewyck** [comment]
> 1. Quantiles implies 4 bins so nBins slide should be disabled for quantiles and it should be fixed to 4

Quantiles can be any number of groups. Quartiles are fixed to 4. So, unless you still want to change, for now I still allowed values different from 4.

> 5. last bin should start with max value

When choosing user-defined, we currently take [hard-coded break values](https://github.com/inbo/alien-species-portal/blob/fix_v1.1.0/alienSpecies/R/mapRegions.R#L505-L540) as defined in the past for the groups, depending on the chosen unit for outcome. If needed, we can change this to depend on the data, e.g. taking quantiles as first suggestion for the breaks which can be further modified by the user. Also, for user-defined both the labels and values can be changed by the user, so 'name' and 'break' will not necessarily match (freedom to the user).

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
@mvarewyck in the latest version it looks like you moved the whole links page to the risk assessment page. it should be displayed only on the links page.

**Comment by SanderDevisscher** [comment]
> > 1. Quantiles implies 4 bins so nBins slide should be disabled for quantiles and it should be fixed to 4
> 
> Quantiles can be any number of groups. Quartiles are fixed to 4. So, unless you still want to change, for now I still allowed values different from 4.

My bad 😅 ok like it is now!
> 
> > 5. last bin should start with max value
> 
> When choosing user-defined, we currently take [hard-coded break values](https://github.com/inbo/alien-species-portal/blob/fix_v1.1.0/alienSpecies/R/mapRegions.R#L505-L540) as defined in the past for the groups, depending on the chosen unit for outcome. If needed, we can change this to depend on the data, e.g. taking quantiles as first suggestion for the breaks which can be further modified by the user. Also, for user-defined both the labels and values can be changed by the user, so 'name' and 'break' will not necessarily match (freedom to the user).

After meeting with @soriadelva we think using "uniform" with 4 bins as first suggestion is the best starting situation. 

Additionally there are some other remaining issues, namely

- [ ] typing a name has the same issues with usability like breaks (which is fixed now).
- [ ] since names & breaks are unrelated I would suggest displaying both in graph if they are not equal (bvb lage aanwezigheid (0-44))

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
"Aantal nieuw geïntroduceerde soorten per jaar" throws an error stating `non-numeric argument to binary operator`

**Comment by SanderDevisscher** [comment]
> "Aantal nieuw geïntroduceerde soorten per jaar" throws an error stating `non-numeric argument to binary operator`

same with Cumulatief aantal geïntroduceerde soorten

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
Bij "Geïntroduceerde soorten per introductieroute (CBD, niveau 1) - trends" I get the following message and no graph:
`In argument: bins_first_observed = floor((.data$first_observed - from)/bin) * bin + from.`

**Comment by mvarewyck** [comment]
> "Aantal nieuw geïntroduceerde soorten per jaar" throws an error stating `non-numeric argument to binary operator`

It's due to new "data_input_checklist_indicators.tsv" data which was not created with the latest createTabularData() function yet. I've updated by hand once.
https://github.com/inbo/alien-species-portal/blob/fix_v1.1.0/alienSpecies/R/data_create.R#L472-L473

**Comment by mvarewyck** [comment]
> Bij "Geïntroduceerde soorten per introductieroute (CBD, niveau 1) - trends" I get the following message and no graph: `In argument: bins_first_observed = floor((.data$first_observed - from)/bin) * bin + from.`

It was due to the same data issue: `first_observed` was no longer numeric - fixed now

**Comment by SanderDevisscher** [comment]
Both issues with data types seem fixed. I'm testing if the files get overwritten by the github actions if they are run with the alienspecies version from this branch. 

[upload_files_processing](https://github.com/inbo/aspbo/actions/workflows/upload_files_processing.yaml)
[upload_files_direct](https://github.com/inbo/aspbo/actions/workflows/upload_files_direct.yaml)

These issue still remain though: 

- [x]  typing a name has the same issues with usability like breaks (which is fixed now).
- [x]  since names & breaks are unrelated I would suggest displaying both in graph if they are not equal (bvb lage aanwezigheid (0-44))

**Comment by mvarewyck** [comment]
> * typing a name has the same issues with usability like breaks (which is fixed now).
> * [ ]   since names & breaks are unrelated I would suggest displaying both in graph if they are not equal (bvb lage aanwezigheid (0-44))

That's correct, I'm still improving the bins selection

**Comment by SanderDevisscher** [comment]
The data seems to not be overwritten by the aspbo github actions 🥳

**Comment by mvarewyck** [comment]
@SanderDevisscher I've implemented all changes.

**Comment by SanderDevisscher** [comment]
Deploying to uat [.github/workflows/deployment_uat.yml](https://github.com/inbo/alien-species-portal/actions/workflows/deployment_uat.yml)

**Comment by SanderDevisscher** [comment]
@mvarewyck there seems to be something wrong with the invasion history maps. When I select municipalities its says there is no data. While all other levels do show data. I've tried uploading the files (direct & processing<sup>1</sup>) with this version of the alien species portal as well as via cube preprocessing<sup>1</sup>, all without effect.

<sup>1</sup>manual dispatch on test_v1.1.0 branch

**Review by SanderDevisscher — APPROVED** [review]

**Pull request merged**
