### PR TITLE
Create report fails #104

### LINKED ISSUE #104: Create report fails on exoten-uat.inbo.be
Should be fixed :
- [ ] clicking `create report` results in a timeout

_Originally posted by @SanderDevisscher in https://github.com/inbo/alien-species-portal/pull/74#pullrequestreview-2082509713_

### PR DESCRIPTION
**Pull request by mvarewyck**
Fix #104 : Replacing webshot by webshot2 and update dockerfile accordingly

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
deploying to UAT [.github/workflows/deployment_uat.yml](https://github.com/inbo/alien-species-portal/actions/workflows/deployment_uat.yml)

**Comment by SanderDevisscher** [comment]
@mvarewyck the deployment fails on:
ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get install --no-install-recommends -y     libgdal-dev     libudunits2-dev     libharfbuzz-dev     libfribidi-dev     libproj22     libgeos3.10.2 libgeos-c1v5      libcurl4-openssl-dev     curl     imagemagick     lbzip2     pandoc     libmagick++-dev     libssl-dev     texlive-latex-extra     lmodern     wget &&     wget https://downloads.vivaldi.com/stable/vivaldi-stable_5.5.2805.35-1_amd64.deb &&     apt-get install --no-install-recommends -y ./vivaldi-stable_5.5.2805.35-1_amd64.deb &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Error: Process completed with exit code 1.

**Comment by SanderDevisscher** [comment]
Should I ask @TheJenne18 to take a look ?

**Comment by mvarewyck** [comment]
> Should I ask @TheJenne18 to take a look ?

Yes please, Tobia is OoO. I have just built the docker image on an AMD machine.

**Comment by mvarewyck** [comment]
> > Should I ask @TheJenne18 to take a look ?
> 
> Yes please, Tobia is OoO. I have just built the docker image on an AMD machine.

Tobia has fixed the dockerfile, it should work now.

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
Deployment succeeds now but creating report still fails.
It seems to fail on the indicators. 
I've tried both Abies alba and Gyrodactylus proterorhini. 
The build hash points to https://github.com/inbo/alien-species-portal/commit/31b40f8191a13de83b074e51b4077af98b92a05f

and this is my sessioninfo:
```
R version 4.3.2 (2023-10-31)
Platform: aarch64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/aarch64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/aarch64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.45         shiny_1.8.0        alienSpecies_1.0.1

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3    rstudioapi_0.15.0     jsonlite_1.8.8       
  [4] magrittr_2.0.3        farver_2.1.1          rmarkdown_2.25       
  [7] vctrs_0.6.5           memoise_2.0.1         config_0.3.2         
 [10] base64enc_0.1-3       terra_1.7-71          htmltools_0.5.7      
 [13] curl_5.2.0            svDialogs_1.1.0       sass_0.4.8           
 [16] KernSmooth_2.23-22    bslib_0.6.1           htmlwidgets_1.6.4    
 [19] fontawesome_0.5.2     plyr_1.8.9            testthat_3.2.1       
 [22] plotly_4.10.4         cachem_1.0.8          whisker_0.4.1        
 [25] mime_0.12             lifecycle_1.0.4       pkgconfig_2.0.3      
 [28] webshot2_0.1.1        Matrix_1.6-1.1        R6_2.5.1             
 [31] fastmap_1.1.1         digest_0.6.34         showtext_0.9-6       
 [34] colorspace_2.1-0      patchwork_1.2.0       shinycssloaders_1.1.0
 [37] ps_1.7.6              aws.signature_0.6.0   crosstalk_1.2.1      
 [40] leaflet.extras_1.0.0  labeling_0.4.3        fansi_1.0.6          
 [43] httr_1.4.7            mgcv_1.9-0            compiler_4.3.2       
 [46] proxy_0.4-27          bit64_4.0.5           withr_3.0.0          
 [49] DBI_1.2.2             trias_2.3.1           aws.ec2metadata_0.2.0
 [52] gratia_0.8.9.14       leaflet_2.2.1         classInt_0.4-10      
 [55] oai_0.4.0             tools_4.3.2           chromote_0.2.0       
 [58] units_0.8-5           httpuv_1.6.14         rgbif_3.7.9          
 [61] glue_1.7.0            nlme_3.1-163          promises_1.2.1       
 [64] grid_4.3.2            sf_1.0-15             reshape2_1.4.4       
 [67] generics_0.1.3        gtable_0.3.4          tzdb_0.4.0           
 [70] class_7.3-22          tidyr_1.3.1           websocket_1.4.1      
 [73] data.table_1.15.0     hms_1.1.3             xml2_1.3.6           
 [76] utf8_1.2.4            pillar_1.9.0          stringr_1.5.1        
 [79] ggspatial_1.1.9       later_1.3.2           splines_4.3.2        
 [82] dplyr_1.1.4           lattice_0.21-9        showtextdb_3.0       
 [85] bit_4.0.5             tidyselect_1.2.0      bookdown_0.37        
 [88] xfun_0.42             brio_1.1.4            DT_0.32              
 [91] stringi_1.8.3         lazyeval_0.2.2        yaml_2.3.8           
 [94] ggokabeito_0.1.0      evaluate_0.23         codetools_0.2-19     
 [97] tibble_3.2.1          cli_3.6.2             arrow_14.0.2.1       
[100] xtable_1.8-4          munsell_0.5.0         processx_3.8.3       
[103] jquerylib_0.1.4       svGUI_1.0.1           Rcpp_1.0.12          
[106] oaStyle_0.4.6         tidyverse_2.0.0       ellipsis_0.3.2       
[109] ggplot2_3.5.0         readr_2.1.5           assertthat_0.2.1     
[112] mvnfast_0.2.8         aws.s3_0.3.21         INBOtheme_0.5.9      
[115] viridisLite_0.4.2     scales_1.3.0          sysfonts_0.8.8       
[118] e1071_1.7-14          purrr_1.0.2           crayon_1.5.2         
[121] rlang_1.1.3           shinyjs_2.1.0        
```

@TheJenne18 can you deliver the logs from 23/08/2024 16:43 ?

**Comment by TheJenne18** [comment]
@SanderDevisscher all logs can be found in here: https://github.com/inbo/alien-species-portal/actions/runs/10525243509/job/29163626591

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher all logs can be found in here: https://github.com/inbo/alien-species-portal/actions/runs/10525243509/job/29163626591

@TheJenne18 I mean the app logs for when it has a timeout. Not the build logs since it builds succesfully.

**Comment by mvarewyck** [comment]
We have run some tests on our side. It seems to fail due to a timeout in the connection to timeseries data. I've implemented a fix, so we can try to test again @SanderDevisscher .

> @TheJenne18 I mean the app logs for when it has a timeout. Not the build logs since it builds succesfully.

This would still be useful, I'm not sure it was the same error as Sander had.

**Comment by mvarewyck** [comment]
Also fixes #101 ?

**Comment by SanderDevisscher** [comment]
deployment is succesfull [.github/workflows/deployment_uat.yml](https://github.com/inbo/alien-species-portal/actions/workflows/deployment_uat.yml)

**Comment by SanderDevisscher** [comment]
#101 seems to be fixed but #104 persists. 
The app still times out but I now get to downloading a corrupted `.htm` file. 
image

This might indicate the previous error was fixed. 

@TheJenne18 can you provide either access to the app logs for @mvarewyck, @soriadelva and me or the app logs from 5m ago (approx. 13h20) ?

**Comment by mvarewyck** [comment]
@SanderDevisscher : Tobia has set up a shinyproxy with 1G and then the app crashes now and then. When setting memory to 2Gi the app doesn't fail with the latest dockerfile and can create the reports for "Xenopis laevis" and "Lithobates catesbeianus". So, we'll need the log files to further debug. @TheJenne18 what is the current memory?

**Comment by SanderDevisscher** [comment]
@TheJenne18 has detected the following error in the app logs:
```
! Failed to start chrome. Error: [0829/112302.960321:ERROR:zygote_host_impl_linux.cc(99)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

**Comment by SanderDevisscher** [comment]
1CPU en 4GB memory

**Comment by SanderDevisscher** [comment]
Deployment has failed again see https://github.com/inbo/alien-species-portal/actions/runs/10684767109/job/29615978749

**Comment by mvarewyck** [comment]
> Deployment has failed again see https://github.com/inbo/alien-species-portal/actions/runs/10684767109/job/29615978749

It looks like a (temporary) downtime of the CRAN repository. I've just restarted the job :crossed_fingers:

**Comment by mvarewyck** [comment]
Build succeeded.
I have restarted the build to include the latest fix: https://github.com/inbo/alien-species-portal/actions/runs/10718473259

**Comment by SanderDevisscher** [comment]
report creation keeps failing

**Comment by SanderDevisscher** [comment]
#115 seems to be fixed, @soriadelva can you confirm ?

**Comment by mvarewyck** [comment]
> report creation keeps failing

@TheJenne18 Can you check whether we get a different error now?

**Comment by soriadelva** [comment]
@mvarewyck these are the logs of the last crash: 
logs

**Comment by SanderDevisscher** [comment]
@mvarewyck creating a report keeps causing a timeout. @TheJenne18 can you provide the logs from between 13:15 & 13:20 today (16/09/24) ?

**Comment by mvarewyck** [comment]
> @mvarewyck creating a report keeps causing a timeout. @TheJenne18 can you provide the logs from between 13:15 & 13:20 today (16/09/24) ?

Our fix wasn't picked up correctly. I've just started a new build.

**Review by SanderDevisscher — APPROVED** [review]

**Pull request merged**
