### PR TITLE
fix for timeseries processing aspbo + R CMD check

### PR DESCRIPTION
**Pull request by mvarewyck**
Related to https://github.com/inbo/aspbo/pull/46

### CODE REVIEW

**Comment by SanderDevisscher** [comment]
@mvarewyck are there any tests I can/need to do?

**Comment by mvarewyck** [comment]
> @mvarewyck are there any tests I can/need to do?

@SanderDevisscher You can test by running the pipeline for [aspbo](https://github.com/inbo/aspbo/pull/46) which uses the new `createTimeseries()` function. 

The PRs are a bit nested. The aspbo needs to be run to create the raw timeseries data on the bucket, and it will use the updated version of this package to create the cleaned timeseries data.

**Review by SanderDevisscher — CHANGES_REQUESTED** [review]
@mvarewyck or @Yingjie-ZhangOA can you add the region parameter (region = "eu-west-1") to the save/put functions used to save processed data to the s3 bucket? 

PS I get a permanent redirect error which seems to be fixed by adding this parameter.

**Comment by mvarewyck** [comment]
> @mvarewyck or @Yingjie-ZhangOA can you add the region parameter (region = "eu-west-1") to the save/put functions used to save processed data to the s3 bucket?
> 
> PS I get a permanent redirect error which seems to be fixed by adding this parameter.

I don't understand where we need to add this parameter. 
For saving data to the bucket we use `aws.s3::s3save()` which only has a `bucket` parameter and no `region` parameter.
For setting up the connection to the S3 bucket, we define an environment variable for the `region`.

@SanderDevisscher Can you maybe copy the error message, to see what you tried and where it fails?

**Comment by mvarewyck** [comment]
> I don't understand where we need to add this parameter.

I think I see here what you mean: https://github.com/inbo/aspbo/pull/46/commits/5f2088a6876cbe21efacf77fe7d6ddafe62a4902

You want me to do the same for all `aws.s3::s3save()` in the alienSpecies package.

**Review by SanderDevisscher — APPROVED** [review]

**Pull request merged**
